name: Deploy static content to Pages

on:
  push:
    branches:
      - master  # O la rama principal de tu repositorio
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build
        run: npm install

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'src/main/resources/static'  # Asegúrate de que esta ruta es correcta

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
